### ISSUE TITLE
how is the .env being imported?

### ISSUE THREAD

**Issue by singha53-zz** [alexa-samples/skill-sample-nodejs-college-finder#19]
Hi,
I had to add require('dotenv').config() to the config.js file to make the env variables accessible locally. The lines below:

aws lambda update-function-configuration --function-name ask-custom-University-Finder-default --environment Variables={SKILL_ID=YOURSKILLID,LIST_IMAGE=https://s3.amazonaws.com/YOURS3BUCKET/image.jpg,API_KEY=YOURAPIKEY,GRAD_IMAGE=https://s3.amazonaws.com/YOURS3BUCKET/image-2.jpg,MAIN_IMAGE=https://s3.amazonaws.com/YOURS3BUCKET/image-3.jpg}

add env variables in the aws console, but not locally. I am wondering if there is way of testing the code without requiring dotenv?
A

**Comment by dievaa** [comment]
Since this is related to the AWS environment, I would recommend reaching out to AWS support who will be able to provide more information on this issue.

AWS Support: https://support.console.aws.amazon.com/support/
